### ISSUE TITLE
IsItemExpandable use

### ISSUE THREAD

**Issue by lesormonde** [KinematicSystems/NSOutlineViewReorder#3]
In the dataSource, isItemExpandable(...)  returns true  if item is a folderItem. 

However if items.count  in the folderItem in question  is 0, you might want to return false so as not to get the exposure triangle when the folder is empty. 

I have found that returning false when folderItem.items.isempty leads to the drop failing. 
Returning folderItem.items.isempty && dragIsInProgress  also seems to fail. 
Any thoughts?

**Comment by KinematicSystems** [comment]
Empty folders show the disclosure triangle in OSX.  Creating a folder in the Finder is an example.   So the behavior is consistent.

**Comment by lesormonde** [comment]
Matt,

I didn’t know that.     
Seems untidy to me.
Anyway, thanks for the response. 

Les Ormonde 
CoDynamics 
Phone:   01865 408027 
Fax:       01865 408027 
Mobile:   07976 920186 
Skype:   lesormonde
Web:      www.codynamics.co.uk <http://www.codynamics.co.uk/>
             www.aufaitmanagement.co.uk <http://www.aufaitmanagement.co.uk/>	
Blog:      lesormonde.wordpress.com <http://lesormonde.wordpress.com/>
Twitter:   twitter.com/lesormonde	 <http://twitter.com/lesormonde%09>

CoDynamics is a trading name of Au Fait Management Ltd. which is registered in England - Number 5189723 
Registered Offices: c/o  Pearson Buchholz, Units 4 and 5 Swinford Farm, Eynsham, Oxfordshire, OX24 4BL  

This email message is confidential. It may also be legally privileged. If you have received it by mistake, please notify us by e-mail reply to postmaster@aufaitmanagement.co.uk <mailto:postmaster@aufaitmanagement.co.uk> and then delete it from your system; you may not copy this message or disclose its contents to anyone. This communication cannot be guaranteed as secure, without errors and virus free. The sender does not accept liability for any errors or omissions.
